import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#131b2e",
        "on-background": "#dae2fd",
        "on-tertiary-container": "#314163",
        "surface-tint": "#e4c285",
        "outline": "#998f81",
        "on-primary-fixed-variant": "#5a4312",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#39485a",
        "on-secondary": "#233143",
        "background": "#0b1326",
        "on-tertiary-fixed-variant": "#374669",
        "surface-container-highest": "#2d3449",
        "secondary": "#b9c8de",
        "primary": "#e6c487",
        "on-error-container": "#ffdad6",
        "on-surface": "#dae2fd",
        "on-secondary-container": "#a7b6cc",
        "tertiary": "#b8c8f2",
        "surface": "#0b1326",
        "secondary-fixed": "#d4e4fa",
        "on-tertiary": "#203051",
        "surface-container-lowest": "#060e20",
        "primary-fixed-dim": "#e4c285",
        "on-tertiary-fixed": "#081b3b",
        "on-primary-container": "#543d0c",
        "surface-container-high": "#222a3d",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "tertiary-container": "#9dadd5",
        "primary-fixed": "#ffdea4",
        "on-surface-variant": "#d0c5b5",
        "inverse-surface": "#dae2fd",
        "secondary-fixed-dim": "#b9c8de",
        "tertiary-fixed-dim": "#b6c6ef",
        "surface-container": "#171f33",
        "secondary-container": "#39485a",
        "tertiary-fixed": "#d8e2ff",
        "primary-container": "#c9a96e",
        "on-secondary-fixed": "#0d1c2d",
        "outline-variant": "#4d463a",
        "surface-variant": "#2d3449",
        "on-primary": "#412d00",
        "on-primary-fixed": "#261900",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "inverse-primary": "#745a27",
        "border": "#4d463a"
      },
      borderRadius: {
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      boxShadow: {
        'card': '0 2px 12px rgba(0,0,0,0.25), 0 0 1px rgba(201,169,110,0.05)',
        'card-hover': '0 4px 24px rgba(0,0,0,0.35), 0 0 1px rgba(201,169,110,0.1)',
        'inner-glow': 'inset 0 1px 0 rgba(255,255,255,0.03)',
      },
    },
  },
  plugins: [],
};
export default config;
